# Generated by Django 4.2.4 on 2023-08-31 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0002_alter_player_losses_alter_player_wins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started', models.BooleanField(default=False)),
                ('players', models.ManyToManyField(to='player.player')),
            ],
        ),
    ]
